### ISSUE TITLE
It's not possible to set array properties

### ISSUE THREAD

**Issue by gimoteco** [robsoncastilho/FluentBuilder#33]
The following snippet is not working 

``` csharp
    public class SomeClass
    {
        public int[] ints { get; set; }
    }
```

Exception

Nosbor.FluentBuilder.Exceptions.FluentBuilderException : Failed setting default value for field "<ints>k__BackingField" - Object "....SomeClass"
  ----> System.ArgumentException : The number of generic arguments provided doesn't equal the arity of the generic type definition.
Parameter name: instantiation

**Comment by robsoncastilho** [comment]
Now it's possible to set arrays using With() method: With(obj => obj.ints, new [] { 1, 2 }) but arrays are NOT being initialized by default.
